import { test, expect } from "@playwright/test";

// The manifest and icons are generated by Next's metadata file conventions;
// this checks the wiring end to end: the page links the manifest, the
// manifest resolves, and every icon URL it lists actually serves a PNG.
test("the app is installable: manifest linked, resolvable, icons served", async ({ page, request }) => {
  await page.goto("/");
  const href = await page.locator('link[rel="manifest"]').getAttribute("href");
  expect(href).toBeTruthy();

  const manifestRes = await request.get(href!);
  expect(manifestRes.ok()).toBeTruthy();
  const manifest = await manifestRes.json();
  expect(manifest.short_name).toBe("Quiz Hub");
  expect(manifest.display).toBe("standalone");

  for (const icon of manifest.icons as { src: string; type: string }[]) {
    const res = await request.get(icon.src);
    expect(res.status(), `icon ${icon.src}`).toBe(200);
    expect(res.headers()["content-type"], `icon ${icon.src}`).toContain("image/png");
  }

  const appleIcon = await page.locator('link[rel="apple-touch-icon"]').getAttribute("href");
  expect(appleIcon).toBeTruthy();
  const appleRes = await request.get(appleIcon!);
  expect(appleRes.status()).toBe(200);

  // Against the manifest's own value, not a literal: a redesign that moves
  // the stage colour should not have to remember to edit this file, and one
  // that drops the viewport export (as the 2026-09 visual redesign did,
  // taking the meta tag off every page) still fails here.
  await expect(page.locator('meta[name="theme-color"]')).toHaveAttribute("content", manifest.theme_color);
});
